name: Embed code in README

on:
  pull_request:
    branches:
      - main
      - review_branch

jobs:
  my-job:
    steps:
      - name: Markdown Embed Code From File
        uses: tokusumi/markdown-embed-code@v1.0.0
